### ISSUE TITLE
CORS Headers

### ISSUE THREAD

**Issue by antimatter15** [npmjs-cf/flexagon#1]
As of a few days ago, registry.npmjs.cf seems to have stopped sending CORS headers. 

I'm not sure if this is the right place to put this, or if the change has been made intentionally. But it looked like CORS support was a feature: https://github.com/npm/semver.npmjs.com/pull/8#issuecomment-205816932

```
curl --head https://registry.npmjs.cf/lodash

HTTP/1.1 200 OK
Server: cloudflare-nginx
Date: Thu, 21 Apr 2016 00:10:06 GMT
Content-Type: application/json
Connection: keep-alive
Set-Cookie: ...
etag: ....
Cache-Control: max-age=300
Via: 1.1 varnish
Age: 160
X-Served-By: cache-lax1428-LAX
X-Cache: HIT
X-Cache-Hits: 24
X-Timer: S....
Vary: Accept-Encoding
CF-RAY: 296....
```

Thanks!

**Comment by terinjokes** [comment]
Fixed. Result of a configuration change unrelated to `flexagon`. I'll be creating a better place for these types of issues going forward.
